function comp(dna)
     rev = reverse(dna)
     ans= ""
     for i=1:length(rev)
     
        if rev[i]=='A'
           ans=ans*"T"
        elseif rev[i]=='T'
           ans=ans*"A"
        elseif rev[i]=='C'
           ans=ans*"G"
        elseif rev[i]=='G'
           ans=ans*"C"
        end
     end
     println(ans)
end 
comp("CACAGAGGGAGGCTACACAGAAAACTACCTAACGGTCGAATTGTCCGTTCTCTCGCAGCAATTCTTCGCTTCGTATCAAACGAAGGAGTCGACATCTCGCTATGGCGTGAAACCGGTGCTAAACAACCTTTTGGAAGATTCTCCTACATCCAGGGTAGGATCACGGAGACTAGCATAGTCTCAATATGCCTTCCTCCTGCTGAGTGCTCTGTGAAAGGATGCCATGCCCCGGAAATCGCTGATAACAGAGTCACCGAGCAGTGAGGTGCACCAGTGGCCCGGATGATGCACGCGCCAGGCACTAAATGCCGCCAAGCCTTCCCAGAAAGTTAGCGCGGTGCCAAGTACTTAGGCCGAGAAGGGCGGTTTGCCTCTAAGCAAGGAAGGCACGACTGTTCTTTGGTCCTCAAAACAGCACAAAGTTGACACATCGACGAACAAAGTACGAGCACGTCCTAGTTAACAGAAATTCGGATCTATTACCTTCTTGGGCTTAATCTTCCGTAGCAAACGATGGAGGCGGACAGGCGCAAGGCAGAACGTAAACGCGTAAGATTTGTAACGGTAGTTATACTACAAGTGAAGATGACCACAGTGCATTGTCATGGTATGGGCTAGGTGATCATGCCCTGGCTTTTAAAGCTAATAGAATCACAAATAGTGCGCTGTGGCATTCCGGTTCCGGTCTTAGAATTCGGCTGCCTGTCGTACAATCCTGCCCCAAAGGCTTTCTGAGTATCCGTGCGTAGCTAGAATCATCGCCTAGAAAGCTTAGATGCTCAGACGGGGTGTTTTCGGCTAGCGGCACCTACTACGCGCTGTGGCGGGAACCGATCATATGTAACTGTGGTGATACCGTCCAGCCGTTCGGAGAATGTGTTAGAGCGGTTCATTCCGGAGAGTGCCCAGTCCAAATGTTCATACGACTGA")